# nnn quitcd helper generated by misc/quitcd/setup.sh
# Rename this file to match the name of the function
# e.g. ~/.config/fish/functions/n.fish
# or, add the lines to the 'config.fish' file.

function n --wraps nnn --description 'support nnn quit and change directory'
    set -x NNN_COLORS '#51e2d0c652d59f7b
36735673'
    # Block nesting of nnn in subshells
    if test -n "$NNNLVL" -a "$NNNLVL" -ge 1
        echo "nnn is already running"
        return
    end

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "-x" from both lines below,
    # without changing the paths.
    if test -n "$XDG_CONFIG_HOME"
        set -x NNN_TMPFILE "$XDG_CONFIG_HOME/nnn/.lastd"
    else
        set -x NNN_TMPFILE "$HOME/.config/nnn/.lastd"
    end

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The command function allows one to alias this function to `nnn` without
    # making an infinitely recursive alias
    command nnn -e -D -Q -R $argv

    if test -e "$NNN_TMPFILE"
        # nnn writes POSIX shell syntax, whose quoting differs from fish.
        # NUL separation preserves paths containing (or ending in) newlines.
        set -l lastdir (command sh -c '. "$1" && printf "%s\000" "$PWD"' sh "$NNN_TMPFILE" | string split0)
        if set -q lastdir[1]
            cd -- "$lastdir"
        end
        rm -- "$NNN_TMPFILE"
    end
end
