# Set default editor
set -gx EDITOR nvim

# nnn ENV variables
# set -gx NNN_FIFO "/tmp/nnn.fifo"
# set -gx NNN_PLUG 'v:preview-tui'
# set -gx NNN_PREVIEWDIR $XDG_CACHE_HOME/nnn/previews

function fish_greeting
    # Leave this empty to disable the message
end

if status is-interactive
    # Commands to run in interactive sessions can go here
end

# For shell tool thingies
zoxide init fish | source
fzf --fish | source
thefuck --alias | source

function y
    set tmp (mktemp -t "yazi-cwd.XXXXXX")
    yazi $argv --cwd-file="$tmp"
    if read -z cwd <"$tmp"; and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
        builtin cd -- "$cwd"
    end
    rm -f -- "$tmp"
end

# Completions
tailscale completion fish | source

# Aliases
abbr -a ls "eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
abbr -a uu "sudo pacman -Syu && yay -Syu && flatpak update"
abbr -a t "tuxedo todo.txt"
abbr -a ytmp4 "yt-dlp -f \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" --paths ~/Videos/"

# Run fastfetch ONLY on alacritty
if test "$TERM" = alacritty; or test "$TERM" = xterm-ghostty
    fastfetch
end

# Vim mode for fish
fish_vi_key_bindings

function __complete_syncthing
    set -lx COMP_LINE (commandline -cp)
    test -z (commandline -ct)
    and set COMP_LINE "$COMP_LINE "
    /usr/bin/syncthing
end
complete -f -c syncthing -a "(__complete_syncthing)"

# nnn quitcd helper generated by misc/quitcd/setup.sh
# Rename this file to match the name of the function
# e.g. ~/.config/fish/functions/n.fish
# or, add the lines to the 'config.fish' file.

function n --wraps nnn --description 'support nnn quit and change directory'
    set -x NNN_COLORS '#51e2d0c652d59f7b;36735673'
    # Block nesting of nnn in subshells
    if test -n "$NNNLVL" -a "$NNNLVL" -ge 1
        echo "nnn is already running"
        return
    end

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "-x" from both lines below,
    # without changing the paths.
    if test -n "$XDG_CONFIG_HOME"
        set -x NNN_TMPFILE "$XDG_CONFIG_HOME/nnn/.lastd"
    else
        set -x NNN_TMPFILE "$HOME/.config/nnn/.lastd"
    end

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The command function allows one to alias this function to `nnn` without
    # making an infinitely recursive alias
    command nnn -e -D -Q -R $argv

    if test -e "$NNN_TMPFILE"
        # nnn writes POSIX shell syntax, whose quoting differs from fish.
        # NUL separation preserves paths containing (or ending in) newlines.
        set -l lastdir (command sh -c '. "$1" && printf "%s\000" "$PWD"' sh "$NNN_TMPFILE" | string split0)
        if set -q lastdir[1]
            cd -- "$lastdir"
        end
        rm -- "$NNN_TMPFILE"
    end
end
